package data.shipsystems;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.combat.MutableShipStatsAPI;
import com.fs.starfarer.api.combat.ShipAPI;
import com.fs.starfarer.api.combat.ShipEngineControllerAPI.ShipEngineAPI;
import com.fs.starfarer.api.impl.combat.BaseShipSystemScript;

//从高能聚焦修改
public class GatherStarConcentrateMode extends BaseShipSystemScript {

    public void apply(MutableShipStatsAPI stats, String id, State state, float effectLevel) {
        if (state == State.OUT) {
            stats.getMaxSpeed().unmodify(id); // to slow down ship to its regular top speed while powering drive down
            stats.getMaxTurnRate().unmodify(id);
        } else {
            stats.getMaxSpeed().modifyFlat(id, -15f);
            stats.getBeamWeaponRangeBonus().modifyFlat(id, 200f);
            stats.getBeamWeaponDamageMult().modifyPercent(id, 25.0f);
            stats.getBallisticWeaponFluxCostMod().modifyPercent(id, -20.0f);
            stats.getEnergyWeaponFluxCostMod().modifyPercent(id, -20.0f);
            stats.getBallisticRoFMult().modifyPercent(id, 33.0f);
            stats.getEnergyRoFMult().modifyPercent(id, 33.0f);

        }

        if (stats.getEntity() instanceof ShipAPI && false) {
            ShipAPI ship = (ShipAPI) stats.getEntity();
            String key = ship.getId() + "_" + id;
            Object test = Global.getCombatEngine().getCustomData().get(key);
            if (state == State.IN) {
                if (test == null && effectLevel > 0.2f) {
                    Global.getCombatEngine().getCustomData().put(key, new Object());
                    ship.getEngineController().getExtendLengthFraction().advance(1f);
                    for (ShipEngineAPI engine : ship.getEngineController().getShipEngines()) {
                        if (engine.isSystemActivated()) {
                            ship.getEngineController().setFlameLevel(engine.getEngineSlot(), 1f);
                        }
                    }
                }
            } else {
                Global.getCombatEngine().getCustomData().remove(key);
            }
        }
    }
    public void unapply(MutableShipStatsAPI stats, String id) {
        stats.getMaxSpeed().unmodify(id);
        stats.getBeamWeaponDamageMult().unmodify(id);
        stats.getBallisticWeaponFluxCostMod().unmodify(id);
        stats.getEnergyWeaponFluxCostMod().unmodify(id);
        stats.getBallisticRoFMult().unmodify(id);
        stats.getEnergyRoFMult().unmodify(id);
        stats.getBeamWeaponRangeBonus().unmodify(id);
    }

    public StatusData getStatusData(int index, State state, float effectLevel) {
        if (index == 0) {
            return new StatusData("-20% Flux generated by ballistic and energy weapons", false);
        } else if (index == 1) {
            return new StatusData("+33% Ballistic and energy weapon rate of fire", false);
        } else if (index == 2) {
            return new StatusData("+200 Beam weapon range", false);
        } else if (index == 3) {
            return new StatusData("+25% Beam weapon damage", false);
        } else if (index == 4) {
            return new StatusData("-15 Top Speed", true);

        }
        return null;
    }
}
