package data.shipsystems;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.combat.MutableShipStatsAPI;
import com.fs.starfarer.api.combat.ShipAPI;
import com.fs.starfarer.api.combat.ShipEngineControllerAPI.ShipEngineAPI;
import com.fs.starfarer.api.impl.combat.BaseShipSystemScript;

//从加速填弹器修改
public class GatherStarMEinterference extends BaseShipSystemScript {

    public void apply(MutableShipStatsAPI stats, String id, State state, float effectLevel) {
        if (state == State.OUT) {
            stats.getMaxSpeed().unmodify(id); // to slow down ship to its regular top speed while powering drive down
        } else {
            stats.getMaxSpeed().modifyFlat(id, -15f);
            stats.getBallisticWeaponDamageMult().modifyPercent(id, 25f);
            stats.getEnergyWeaponFluxCostMod().modifyPercent(id, -50f);
            stats.getEnergyRoFMult().modifyPercent(id, 50f);
            stats.getBallisticRoFMult().modifyPercent(id, 50f);
            stats.getProjectileSpeedMult().modifyPercent(id, -33f);
        }

        if (stats.getEntity() instanceof ShipAPI && false) {
            ShipAPI ship = (ShipAPI) stats.getEntity();
            String key = ship.getId() + "_" + id;
            Object test = Global.getCombatEngine().getCustomData().get(key);
            if (state == State.IN) {
                if (test == null && effectLevel > 0.2f) {
                    Global.getCombatEngine().getCustomData().put(key, new Object());
                    ship.getEngineController().getExtendLengthFraction().advance(1f);
                    for (ShipEngineAPI engine : ship.getEngineController().getShipEngines()) {
                        if (engine.isSystemActivated()) {
                            ship.getEngineController().setFlameLevel(engine.getEngineSlot(), 1f);
                        }
                    }
                }
            } else {
                Global.getCombatEngine().getCustomData().remove(key);
            }
        }
    }
    public void unapply(MutableShipStatsAPI stats, String id) {
        stats.getMaxSpeed().unmodify(id);
        stats.getBallisticWeaponDamageMult().unmodify(id);
        stats.getEnergyWeaponFluxCostMod().unmodify(id);
        stats.getEnergyRoFMult().unmodify(id);
        stats.getBallisticRoFMult().unmodify(id);
        stats.getProjectileSpeedMult().unmodify(id);
        stats.getEnergyRoFMult().unmodify(id);
    }

    public StatusData getStatusData(int index, State state, float effectLevel) {
        if (index == 0) {
            return new StatusData("+50% ballistic and energy weapon rate of fire", false);
        } else if (index == 1) {
            return new StatusData("-50% flux generated by energy weapons", false);
        } else if (index == 2){
            return new StatusData("+25% ballistic weapon damage", false);
        } else if (index == 3){
            return new StatusData("-33% projectile speed", true);
        } else if (index == 4){
            return new StatusData("-15 top speed", true);
        }
        return null;
    }
}
