package data.shipsystems;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.combat.MutableShipStatsAPI;
import com.fs.starfarer.api.combat.ShipAPI;
import com.fs.starfarer.api.combat.ShipEngineControllerAPI.ShipEngineAPI;
import com.fs.starfarer.api.impl.combat.BaseShipSystemScript;

//从加速填弹器修改
public class HongSeJueMie extends BaseShipSystemScript {

    public void apply(MutableShipStatsAPI stats, String id, State state, float effectLevel) {
        if (state == State.OUT) {
            stats.getMaxSpeed().unmodify(id); // to slow down ship to its regular top speed while powering drive down
            stats.getMaxTurnRate().unmodify(id);
        } else {
            stats.getMaxSpeed().modifyFlat(id, 50f);
            stats.getAcceleration().modifyPercent(id, 100f * effectLevel);
            stats.getDeceleration().modifyPercent(id, 100f * effectLevel);
            stats.getTurnAcceleration().modifyFlat(id, 20f * effectLevel);
            stats.getTurnAcceleration().modifyPercent(id, 100f * effectLevel);
            stats.getMaxTurnRate().modifyFlat(id, 10f);
            stats.getMaxTurnRate().modifyPercent(id, 50f);
            stats.getBeamWeaponDamageMult().modifyPercent(id, 25.0f);
            stats.getBeamWeaponFluxCostMult().modifyPercent(id, -50.0f);
            stats.getBeamWeaponRangeBonus().modifyFlat(id, 500.0f);
            stats.getEnergyRoFMult().modifyPercent(id, 50.0f);
            stats.getPeakCRDuration().modifyFlat(id, -9999f);
        }

        if (stats.getEntity() instanceof ShipAPI && false) {
            ShipAPI ship = (ShipAPI) stats.getEntity();
            String key = ship.getId() + "_" + id;
            Object test = Global.getCombatEngine().getCustomData().get(key);
            if (state == State.IN) {
                if (test == null && effectLevel > 0.2f) {
                    Global.getCombatEngine().getCustomData().put(key, new Object());
                    ship.getEngineController().getExtendLengthFraction().advance(1f);
                    for (ShipEngineAPI engine : ship.getEngineController().getShipEngines()) {
                        if (engine.isSystemActivated()) {
                            ship.getEngineController().setFlameLevel(engine.getEngineSlot(), 1f);
                        }
                    }
                }
            } else {
                Global.getCombatEngine().getCustomData().remove(key);
            }
        }
    }
    public void unapply(MutableShipStatsAPI stats, String id) {
        stats.getMaxSpeed().unmodify(id);
        stats.getMaxTurnRate().unmodify(id);
        stats.getTurnAcceleration().unmodify(id);
        stats.getAcceleration().unmodify(id);
        stats.getDeceleration().unmodify(id);
        stats.getBeamWeaponDamageMult().unmodify(id);
        stats.getBeamWeaponFluxCostMult().unmodify(id);
        stats.getBeamWeaponRangeBonus().unmodify(id);
        stats.getEnergyRoFMult().unmodify(id);
    }

    public StatusData getStatusData(int index, State state, float effectLevel) {
        if (index == 0) {
            return new StatusData("Increase top speed and maneuverability", false);
        } else if (index == 1) {
            return new StatusData("Significantly increase beam range", false);
        } else if (index == 2){
            return new StatusData("+25% beam weapon damage", false);
        } else if (index == 3){
            return new StatusData("-50% flux generated by beam weapons", false);
        } else if (index == 4){
            return new StatusData("+50% energy weapon rate of fire", false);
        } else if (index == 5){
            return new StatusData("Immediately lose all peak performance time", true);
        }
        return null;
    }
}
