package data.campaign.Card;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.CampaignFleetAPI;
import com.fs.starfarer.api.campaign.CargoTransferHandlerAPI;
import com.fs.starfarer.api.campaign.SpecialItemData;
import com.fs.starfarer.api.campaign.impl.items.BaseSpecialItemPlugin;
import com.fs.starfarer.api.characters.OfficerDataAPI;
import com.fs.starfarer.api.characters.PersonAPI;
import com.fs.starfarer.api.ui.TooltipMakerAPI;
import com.fs.starfarer.api.util.Misc;
import data.util.WthC_ColorData;
import data.util.WthC_Util;

// 从幻想工造的军官酒馆事件和双面神等道具缝合而来
public class Crad_Dust2 extends BaseSpecialItemPlugin{

    public static final WthC_Util.I18nSection strings = WthC_Util.I18nSection.getInstance("items", "WthC_");
    protected CampaignFleetAPI player_fleet;
    protected PersonAPI officer;
    protected OfficerDataAPI officer_data;

    @Override
    public String getDesignType() {
        return null;
    }

    @Override
    public void createTooltip(TooltipMakerAPI tooltip, boolean expanded, CargoTransferHandlerAPI transferHandler, Object stackSource) {
        float pad = 15f;
        float padS = 3f;
        
        tooltip.addTitle(getName());

        String design = getDesignType();
        if (design != null) {
            Misc.addDesignTypePara(tooltip, design, 10f);
        }

        if (!spec.getDesc().isEmpty()) {
            tooltip.addPara(spec.getDesc(), Misc.getTextColor(), pad);
        }

        tooltip.addPara("\"It's over...\"", WthC_ColorData.DUST_RED, pad);

        tooltip.addPara("For anyone who participates in war, the battlefield is always a cruel hell. Behind the glory lies only injury, death, and sometimes the plague that follows...", WthC_ColorData.B_WHITE, pad);
        tooltip.addPara("For anyone who initiates war, the battlefield is always a political tool. It seems all conflicts can be resolved here, and victory brings endless benefits to one's faction...", WthC_ColorData.B_WHITE, padS);
        tooltip.addPara("But for you, the battlefield holds nothing... Of course, this isn't some philosophical revelation. It's simply that anything you strike tends to evaporate instantly... leaving no trace...", WthC_ColorData.B_WHITE, padS);

        tooltip.addPara("They were once heroes... fathers... seasoned soldiers... spirited youths... and even geniuses waiting to make their mark... But in the next moment, they all vaporize under the immense energy blade, becoming part of the atmospheric cycle, all equal in death...", WthC_ColorData.B_WHITE, pad);
        tooltip.addPara("So... any war you participate in is utterly boring, devoid of suspense... devoid of artistry... It's merely a monster with absolute power slaughtering without finesse...", WthC_ColorData.B_WHITE, padS);
        tooltip.addPara("In fact... you might not even need to lift a finger. Simply deactivating the shield generated by the ring would allow the fusion reactions naturally emanating from your body to painfully kill all enemies within a minute...", WthC_ColorData.B_WHITE, padS);

        tooltip.addPara("However... no warrior who has the courage to raise their weapon against a stronger foe should die alone in torment and panic...", WthC_ColorData.B_WHITE, pad);
        tooltip.addPara("Even if the afterlife never opens its gates for them, and reincarnation remains a distant dream...", WthC_ColorData.B_WHITE, padS);
        tooltip.addPara("At the very least... in their final moments, they will know... that what took their life was not some unavoidable disease...", WthC_ColorData.B_WHITE, padS);
        tooltip.addPara("But the blade of death itself, wielded by the reaper to harvest souls...", WthC_ColorData.B_WHITE, padS);

        tooltip.addPara("\"A deity who casually takes the lives of mortals is never worthy of praise...\"", WthC_ColorData.DUST_RED, pad);

    }

    @Override
    public float getTooltipWidth() {
        return super.getTooltipWidth();
    }

    @Override
    public boolean isTooltipExpandable() {
        return false;
    }

    @Override
    public boolean hasRightClickAction() {
        return true;
    }

    @Override
    public boolean shouldRemoveOnRightClickAction() {
        return true;
    }

    @Override
    public void performRightClickAction() {
        Global.getSector().getPlayerStats().addStoryPoints(1);
        Global.getSector().getPlayerFleet().getCargo().addSpecial(new SpecialItemData("Crad_Dust3", "special_items"), 1.0F);
        Global.getSector().getCampaignUI().getMessageDisplay().addMessage(
                "This immersive experience is sure to leave a lasting impression on you... You have gained 1 story point.");
    }
}
